import { Squad } from "./types";

export const DEFAULT_TRANSFERS_SQUAD: Squad = [
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "GK",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "GK",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    nowCost: 0,
  },
];
