import { Squad } from "./types";

export const DEFAULT_POINTS_SQUAD: Squad = [
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "GK",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "FWD",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "GK",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "DEF",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
  {
    id: 1,
    name: "",
    team: 1,
    teamShortName: "",
    position: "MID",
    gwPoints: 0,
    isCaptain: false,
    isViceCaptain: false,
    multiplier: 1,
    fixtures: [],
    fixtureIds: [],
    fixturesFinished: [],
    minutes: [],
  },
];
